#!/bin/sh
# postinst script for ancestromania-data
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


if [ ! -e "/var/lib/firebird/2.5/data/Ancestromania.fdb" ]; then
	cp "/var/lib/firebird/2.5/data/Ancestromania-updated.fdb" "/var/lib/firebird/2.5/data/Ancestromania.fdb"
	chmod 660 /var/lib/firebird/2.5/data/Ancestromania.fdb 
fi

chown firebird:firebird /var/lib/firebird/2.5/data/Ancestromania.fdb
chown firebird:firebird /var/lib/firebird/2.5/data/Ancestromania-updated.fdb
chown firebird:firebird /var/lib/firebird/2.5/data/Parances.fdb

## get UID limit ##
l=$(grep "^UID_MIN" /etc/login.defs)

## use awk to print if UID >= $UID_LIMIT ##
for USER in `awk -F':' -v "limit=${l##UID_MIN}" '{ if ( $3 >= limit ) print $1}' /etc/passwd`;do
	echo "setting $USER as firebird member"
	usermod -a -G firebird $USER
done


if [ ! -z `grep Ancestromania /etc/firebird/2.5/aliases.conf -rL` ]; then
    echo "Adding Ancestromania to aliases"
	echo "Parances.fdb=/var/lib/firebird/2.5/data/Parances.fdb\nAncestromania.fdb=/var/lib/firebird/2.5/data/Ancestromania.fdb" >> /etc/firebird/2.5/aliases.conf
#    dpkg-reconfigure firebird2.5-superclassic
    notify-send "Afin d'utiliser Ancestromania, Veuillez fermer votre session."
fi
# End automatically added section

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
