UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('1', 'ABBR', 'Abréviation', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('2', 'ADDR', 'Adresse', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('3', 'ADOP', 'Adoption', '8', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('4', 'ADR1', 'Ligne adresse 1', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('5', 'ADR2', 'Ligne adresse 2', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('6', 'AFN', 'N° Unique', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('7', 'AGE', 'Age de l''individu', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('8', 'AGNC', 'Institution', '11', '1', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('9', 'ALIA', 'Alias', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('10', 'ANCE', 'Ancêtre', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('11', 'ANCI', 'Ascendance à étudier', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('12', 'ANUL', 'Annulation d''une union', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('13', 'ASSO', 'Lien d''associés à un individu', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('14', 'AUTH', 'Auteur', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('15', 'BAPL', 'Baptême Mormons', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('16', 'BAPM', 'Baptême non chrétien', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('17', 'BARM', 'Bar Mitzvah', '3', '1', '1', '0', '1', 'FRA', 'E', '1');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('18', 'BASM', 'Bat Mitzvah', '3', '1', '1', '0', '1', 'FRA', 'E', '1');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('19', 'BENE', 'Utiliser Bénédiction', '1', '0', '1', '0', '1', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('20', 'BIRT', 'Naissance', '0', '1', '1', '-5', '1', 'FRA', 'E', '1');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('21', 'BLES', 'Bénédiction', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('22', 'BLOB', 'Objet binaire', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('23', 'BURI', 'Inhumation/Sépulture', '0', '1', '1', '5', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('24', 'CALN', 'Cote ou n° de classement pièce', '10', '0', '1', '0', '1', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('25', 'CAST', 'Caste', '10', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('26', 'CAUS', 'Cause de l''évènement', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('27', 'CENS', 'Recensement', '10', '1', '1', '0', '1', 'FRA', 'D', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('28', 'CHAN', 'Date de modification', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('29', 'CHAR', 'Jeu de caractère du fichier', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('30', 'CHIL', 'Enfant naturel', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('31', 'CHR', 'Baptême', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('32', 'CHRA', 'Baptême adulte', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('33', 'COMU', 'Communion', '1', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('34', 'CONC', 'Concaténation', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('35', 'CONF', 'Confirmation', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('36', 'CONL', 'Conversion Mormons', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('37', 'CONT', 'Continuer', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('38', 'COPR', 'Copyright', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('39', 'CORP', 'Nom d''une entreprise', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('40', 'CREM', 'Crémation', '0', '1', '1', '4', '1', 'FRA', 'E', '1');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('41', 'CTRY', 'Pays', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('42', 'CITY', 'Ville', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('43', 'DATA', 'Données', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('44', 'DATE', 'Date de l''évènement', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('45', 'DEAT', 'Décès', '0', '1', '1', '3', '1', 'FRA', 'E', '1');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('46', 'DECO', 'Décoration', '6', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('47', 'DESC', 'Descendance', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('48', 'DESI', 'Descendance à étudier', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('49', 'DEST', 'Destinataire', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('50', 'DIPL', 'Utiliser Diplôme', '5', '0', '1', '0', '1', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('51', 'DIV', 'Rupture de l''union (divorce)', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('52', 'DIVF', 'Demande de rupture (divorce)', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('53', 'DSCR', 'Description physique', '6', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('54', 'EDUC', 'Niveau d''instruction', '5', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('55', 'EMIG', 'Émigration', '8', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('56', 'ENDL', 'Cérémonie Mormons ENDL', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('57', 'ENGA', 'Fiançailles', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('58', 'EVEN', 'Divers', '9', '1', '1', '0', '1', 'FRA', 'D', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('59', 'FAM', 'Famille', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('60', 'FAMC', 'Famille d''un enfant', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('61', 'FAMF', 'Fichier famille des mormons', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('62', 'FAMS', 'Famille d''un individu', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('63', 'FCOM', 'Première communion', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('64', 'FILE', 'Fichier', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('65', 'FORM', 'Format de fichier', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('66', 'GEDC', 'Format GEDCOM', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('67', 'GIVN', 'Prénom', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('68', 'GRAD', 'Diplôme', '5', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('69', 'HEAD', 'En-tête GEDCOM', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('70', 'HUSB', 'Mari ou père', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('71', 'IDNO', 'Identifiant d''une personne', '10', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('72', 'IMMI', 'Immigration', '8', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('73', 'INDI', 'Une personne', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('74', 'INHU', 'Utiliser Inhumation/Sépulture', '0', '0', '1', '0', '1', 'FRA', NULL, '1');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('75', 'LANG', 'Langue utilisée', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('76', 'LEGA', 'Légataire', '10', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('77', 'MARB', 'Publication des bans', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('78', 'MARC', 'Contrat régissant l''union', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('79', 'MARL', 'Autorisation légale d''union', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('80', 'MARS', 'Contrat avant union', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('81', 'MEDI', 'Information du support', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('82', 'NAME', 'Nom d''un individu', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('83', 'NATI', 'Nationalité, Peuple ou Tribu', '8', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('84', 'NATU', 'Naturalisation', '8', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('85', 'NCHI', 'Nombre d''enfant', '11', '0', '0', '0', '0', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('86', 'NICK', 'Surnom', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('87', 'NMR', 'Nombre de mariage', '11', '0', '0', '0', '0', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('88', 'NOTE', 'Notes', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('89', 'NPFX', 'Préfixe', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('90', 'NSFX', 'Suffixe', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('91', 'OBJE', 'Description', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('92', 'OCCU', 'Profession', '7', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('93', 'ORDI', 'Ordination Mormons', '1', '0', '1', '0', '1', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('94', 'ORDN', 'Ordination', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('95', 'PAGE', 'N° de page', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('96', 'PEDI', 'Pedigree', '7', '0', '1', '0', '1', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('97', 'PHON', 'Téléphone', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('98', 'PLAC', 'Lieu de l''événement', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('99', 'POST', 'Code postal de l''évènement', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('100', 'PROB', 'Validation d''un testament', '4', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('101', 'PROP', 'Biens et possessions', '10', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('102', 'PUBL', 'Publication d''un ouvrage', '11', '1', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('103', 'QUAY', 'Degré de confiance', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('104', 'REFN', 'N° du fichier', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('105', 'RELA', 'Valeur lien', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('106', 'RELI', 'Religion', '1', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('107', 'REPO', 'Dépositaire de l''info', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('108', 'RESI', 'Domicile', '11', '0', '1', '0', '1', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('109', 'RESN', 'Restriction', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('110', 'RETI', 'Retraite', '4', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('111', 'RFN', 'N° permanent', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('112', 'RIN', 'N° automatique', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('113', 'ROLE', 'Rôle joué par l''individu', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('114', 'SACR', 'Sacre', '6', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('115', 'SEX', 'Sexe', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('116', 'SLGC', 'Cérémonie Mormons SLGC', '1', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('117', 'SLGS', 'Mariage Mormon', '1', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('118', 'SOUR', 'Sources', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('119', 'SPFX', 'Partie pas indexée', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('120', 'SSN', 'N° de SS (USA seulement)', '10', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('121', 'STAE', 'Etat', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('122', 'STAT', 'Statut', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('123', 'SUBM', 'Origine des données', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('124', 'SURN', 'Surnom de famille', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('125', 'TEMP', 'Nom/n° code temple Mormon', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('126', 'TIME', 'Heure', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('127', 'TITL', 'Titre', '6', '1', '1', '0', '1', 'FRA', 'A', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('128', 'TITR', 'Utiliser Titre', '10', '0', '1', '0', '1', 'FRA', NULL, '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('129', 'TRLR', 'Fin de fichier GEDCOM', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('130', 'TYPE', 'Définition complémentaire', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('131', 'VERS', 'Version du produit', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('132', 'VOYA', 'Voyage', '9', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('133', 'WIFE', 'Epouse', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('134', 'WILL', 'Testament (rédaction)', '4', '1', '1', '0', '1', 'FRA', 'E', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('135', 'MARR', 'Union (Mariage)', '2', '1', '1', '0', '1', 'FRA', 'U', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('136', 'PURC', 'Acquisition', '10', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('137', 'ALIV', 'Vivant', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('138', 'MILI', 'Service militaire', '6', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('139', 'SALE', 'Vente', '10', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('140', 'TRIP', 'Voyage long', '9', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('141', 'BRIT', 'Brit Mila', '3', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('142', 'LIEU', 'Lieu dit', '11', '0', '1', '0', '1', 'FRA', ' ', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('143', 'X_MU1', 'Circoncision', '12', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('144', 'X_MU2', 'Chahada', '12', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('145', 'X_MU3', 'El hadj', '12', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('146', 'XSPO', 'Sports', '13', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('147', 'XLOI', 'Loisirs', '14', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('148', 'XHENN', 'Henné - Fiançailles', '3', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('149', 'XHOUP', 'Houpa - Bénéd. religieuse', '3', '0', '1', '0', '1', 'FRA', 'T', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('150', 'IDSPE', 'Père introuvable', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('151', 'IDSME', 'Mère introuvable', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('152', 'IDSPA', 'Parents introuvables', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('762', 'IDSPE', 'Père introuvable', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('763', 'IDSME', 'Mère introuvable', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('764', 'IDSPA', 'Parents introuvables', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('765', 'IDSPE', 'Père introuvable', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('766', 'IDSME', 'Mère introuvable', '10', '0', '0', '0', '0', 'FRA', 'I', '0');
UPDATE OR INSERT INTO REF_EVENEMENTS (REF_EVE_CODE, REF_EVE_LIB_COURT, REF_EVE_LIB_LONG, REF_EVE_CAT, REF_EVE_VISIBLE, REF_EVE_A_TRAITER, REF_EVE_ECRAN, REF_EVE_OBLIGATOIRE, REF_EVE_LANGUE, REF_EVE_TYPE, REF_EVE_UNE_FOIS) VALUES ('767', 'IDSPA', 'Parents introuvables', '10', '0', '0', '0', '0', 'FRA', 'I', '0');

UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('1', '(inconnu)', 'FRA', 'Other');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('2', 'parrain', 'FRA', 'Godfather');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('3', 'marraine', 'FRA', 'Godmother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('4', 'officier d''état civil', 'FRA', 'Registry officer');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('5', 'officier religieux', 'FRA', 'Officiating priest');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('6', 'gendarme', 'FRA', 'Gendarme');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('7', 'médecin', 'FRA', 'Doctor');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('8', 'membre de la famille', 'FRA', 'Family''s member');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('9', 'ami de la famille', 'FRA', 'Family''s friend');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('10', 'militaire', 'FRA', 'Soldier');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('11', 'cousin', 'FRA', 'Cousin');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('12', 'cousine', 'FRA', 'Cousin (f)');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('13', 'grand-père', 'FRA', 'Grandfather');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('14', 'grand-mère', 'FRA', 'Grandmother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('15', 'mère', 'FRA', 'Mother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('16', 'père', 'FRA', 'Father');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('17', 'frère', 'FRA', 'Brother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('18', 'sœur', 'FRA', 'Sister');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('19', 'témoin', 'FRA', 'Witness');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('20', 'déclarant', 'FRA', 'Declarant');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('21', 'présent', 'FRA', 'Person present');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('22', 'époux', 'FRA', 'Husband');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('23', 'épouse', 'FRA', 'Wife');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('24', 'fils', 'FRA', 'Son');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('25', 'fille', 'FRA', 'Daughter');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('26', 'gendre', 'FRA', 'Son-in-law');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('27', 'bru', 'FRA', 'Daughter-in-law');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('28', 'petit-fils', 'FRA', 'Grandson');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('29', 'petite-fille', 'FRA', 'Granddaugther');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('30', 'beau-frère', 'FRA', 'Brother-in-law');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('31', 'belle-sœur', 'FRA', 'Sister-in-law');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('32', 'oncle', 'FRA', 'Uncle');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('33', 'tante', 'FRA', 'Aunt');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('34', 'aïeul', 'FRA', 'Ancestor');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('35', 'belle-fille (fille conjoint)', 'FRA', 'Stepdaughter');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('36', 'père adoptif', 'FRA', 'Adoptive father');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('37', 'mère adoptive', 'FRA', 'Adoptive mother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('38', 'père nourricier', 'FRA', 'Foster father');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('39', 'mère nourricière', 'FRA', 'Foster mother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('40', 'neveu', 'FRA', 'Nephew');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('41', 'nièce', 'FRA', 'Niece');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('42', 'beau-fils (fils du conjoint)', 'FRA', 'Stepson');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('43', 'beau-père (père du conjoint)', 'FRA', 'Father-in-law');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('44', 'beau-père (époux de la mère)', 'FRA', 'Stepfather');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('45', 'belle-mère (mère du conjoint)', 'FRA', 'Mother-in-law');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('46', 'belle-mère (épouse du père)', 'FRA', 'Stepmother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('47', 'demi-frère', 'FRA', 'Half-brother');
UPDATE OR INSERT INTO REF_RELA_TEMOINS (REF_RELA_CLEF, REF_RELA_LIBELLE, LANGUE, REF_RELA_TAG) VALUES ('48', 'demi-sœur', 'FRA', 'Half-sister');

SET TERM ^ ;

ALTER PROCEDURE PROC_LISTE_PARENTE (INDI1 INTEGER,
INDI2 INTEGER)
RETURNS (ANCETRE_1 INTEGER,
NOM_1 VARCHAR(130) CHARACTER SET ISO8859_1,
SEXE_1 INTEGER,
SOSA_1 INTEGER,
ANCETRE_2 INTEGER,
NOM_2 VARCHAR(130) CHARACTER SET ISO8859_1,
SEXE_2 INTEGER,
SOSA_2 INTEGER)
AS 
declare variable enfant_1 integer;
declare variable nom_enfant_1 varchar(130);
declare variable sexe_enfant_1 integer;
declare variable sosa_enfant_1 integer;
declare variable enfant_2 integer;
declare variable nom_enfant_2 varchar(130);
declare variable sexe_enfant_2 integer;
declare variable sosa_enfant_2 integer;
declare variable i integer;
declare variable i_1 integer;
declare variable i_2 integer;
begin
  select first(1) p.commun
        ,i.nom||coalesce(' '||i.prenom,'')||case 
          when ((i.annee_naissance is null) and (i.annee_deces is null)) then ''
          when (i.annee_naissance is null) then ' (†'||cast(i.annee_deces as varchar(5))||')'
          when (i.annee_deces is null) then ' (°'||cast(i.annee_naissance as varchar(5))||')'
          else ' (°'||cast(i.annee_naissance as varchar(5))||' †'||cast(i.annee_deces as varchar(5))||')'
          end
        ,i.sexe
        ,case when i.num_sosa>0 then 1 else 0 end
        ,p.enfant_1
        ,e1.nom||coalesce(' '||e1.prenom,'')||case
          when ((e1.annee_naissance is null) and (e1.annee_deces is null)) then ''
          when (e1.annee_naissance is null) then ' (†'||cast(e1.annee_deces as varchar(5))||')'
          when (e1.annee_deces is null) then ' (°'||cast(e1.annee_naissance as varchar(5))||')'
          else ' (°'||cast(e1.annee_naissance as varchar(5))||' †'||cast(e1.annee_deces as varchar(5))||')'
          end
        ,e1.sexe
        ,case when e1.num_sosa>0 then 1 else 0 end
        ,p.enfant_2
        ,e2.nom||coalesce(' '||e2.prenom,'')||case
          when ((e2.annee_naissance is null) and (e2.annee_deces is null)) then ''
          when (e2.annee_naissance is null) then ' (†'||cast(e2.annee_deces as varchar(5))||')'
          when (e2.annee_deces is null) then ' (°'||cast(e2.annee_naissance as varchar(5))||')'
          else ' (°'||cast(e2.annee_naissance as varchar(5))||' †'||cast(e2.annee_deces as varchar(5))||')'
          end
        ,e2.sexe
        ,case when e2.num_sosa>0 then 1 else 0 end
        ,p.niveau_min_1
        ,p.niveau_min_2
        from proc_anc_communs(:indi1,:indi2) p
        inner join individu i on i.cle_fiche=p.commun
        inner join individu e1 on e1.cle_fiche=p.enfant_1
        inner join individu e2 on e2.cle_fiche=p.enfant_2
        order by p.niveau_min_1+p.niveau_min_2
  into :ancetre_1
      ,:nom_1
      ,:sexe_1
      ,:sosa_1
      ,:enfant_1
      ,:nom_enfant_1
      ,:sexe_enfant_1
      ,:sosa_enfant_1
      ,:enfant_2
      ,:nom_enfant_2
      ,:sexe_enfant_2
      ,:sosa_enfant_2
      ,:i_1
      ,:i_2;
  ancetre_2=ancetre_1;
  nom_2=nom_1;
  sexe_2=sexe_1;
  sosa_2=sosa_1;
  if (ancetre_1>0) then
    suspend;
  else
    exit;
  if (enfant_1>0 or enfant_2>0) then
  begin
    if (enfant_1<>ancetre_1) then
    begin
      ancetre_1=enfant_1;
      nom_1=nom_enfant_1;
      sexe_1=sexe_enfant_1;
      sosa_1=sosa_enfant_1;
    end
    else
    begin
      ancetre_1=0;
      nom_1=null;
      sexe_1=0;
      sosa_1=0;
    end
    if (enfant_2<>ancetre_2) then
    begin
      ancetre_2=enfant_2;
      nom_2=nom_enfant_2;
      sexe_2=sexe_enfant_2;
      sosa_2=sosa_enfant_2;
    end
    else
    begin
      ancetre_2=0;
      nom_2=null;
      sexe_2=0;
      sosa_2=0;
    end
    suspend;
  end
  else
    exit;
  i=1;
  while (i<i_1 or i<i_2) do
  begin
    ancetre_1=0;
    ancetre_2=0;
    nom_1=null;
    nom_2=null;
    sexe_1=0;
    sexe_2=0;
    if (i<i_1) then
    begin
      select first(1) t.enfant
        ,i.nom||coalesce(' '||i.prenom,'')||case
          when ((i.annee_naissance is null) and (i.annee_deces is null)) then ''
          when (i.annee_naissance is null) then ' (†'||cast(i.annee_deces as varchar(5))||')'
          when (i.annee_deces is null) then ' (°'||cast(i.annee_naissance as varchar(5))||')'
          else ' (°'||cast(i.annee_naissance as varchar(5))||' †'||cast(i.annee_deces as varchar(5))||')'
          end
        ,i.sexe
        ,case when i.num_sosa>0 then 1 else 0 end
      from tq_anc t
      inner join individu i on i.cle_fiche=t.enfant
      where t.decujus=:indi1 and t.indi=:enfant_1 and t.niveau=:i_1-:i
      into :ancetre_1
          ,:nom_1
          ,:sexe_1
          ,:sosa_1;
      enfant_1=ancetre_1;
    end
    else
    begin
      ancetre_1=0;
      nom_1=null;
      sexe_1=0;
      sosa_1=0;
    end
    if (i<i_2) then
    begin
      select first(1) t.enfant
        ,i.nom||coalesce(' '||i.prenom,'')||case
          when ((i.annee_naissance is null) and (i.annee_deces is null)) then ''
          when (i.annee_naissance is null) then ' (†'||cast(i.annee_deces as varchar(5))||')'
          when (i.annee_deces is null) then ' (°'||cast(i.annee_naissance as varchar(5))||')'
          else ' (°'||cast(i.annee_naissance as varchar(5))||' †'||cast(i.annee_deces as varchar(5))||')'
          end
        ,i.sexe
        ,case when i.num_sosa>0 then 1 else 0 end
      from tq_anc t
      inner join individu i on i.cle_fiche=t.enfant
      where t.decujus=:indi2 and t.indi=:enfant_2 and t.niveau=:i_2-:i
      into :ancetre_2
          ,:nom_2
          ,:sexe_2
          ,:sosa_2;
      enfant_2=ancetre_2;
    end
    else
    begin
      ancetre_2=0;
      nom_2=null;
      sexe_2=0;
      sosa_2=0;
    end
    suspend;
    i=i+1;
  end
end  ^


ALTER PROCEDURE PROC_NAVIGATION (I_CLEF INTEGER,
I_MAX INTEGER)
RETURNS (NIVEAU INTEGER,
CLE_FICHE INTEGER,
NOM VARCHAR(60) CHARACTER SET ISO8859_1,
PRENOM VARCHAR(100) CHARACTER SET ISO8859_1,
DATE_NAISSANCE VARCHAR(100) CHARACTER SET ISO8859_1,
DATE_DECES VARCHAR(100) CHARACTER SET ISO8859_1,
SEXE INTEGER,
CLE_PERE INTEGER,
CLE_MERE INTEGER,
SOSA DOUBLE PRECISION,
DECEDE INTEGER,
VILLE_NAISSANCE VARCHAR(50) CHARACTER SET ISO8859_1,
VILLE_DECES VARCHAR(50) CHARACTER SET ISO8859_1,
PROFESSION VARCHAR(90) CHARACTER SET ISO8859_1,
DATE_UNION VARCHAR(90) CHARACTER SET ISO8859_1,
VILLE_UNION VARCHAR(50) CHARACTER SET ISO8859_1,
PHOTO BLOB,
ENFANTS INTEGER,
NUM_SOSA DOUBLE PRECISION,
PERIODE_VIE VARCHAR(15) CHARACTER SET ISO8859_1)
AS 
declare variable i_sexe integer;
declare variable i_cle_pere integer;
declare variable i_cle_mere integer;
declare variable i_cle_pere_pere integer;
declare variable i_cle_pere_mere integer;
declare variable i_cle_mere_pere integer;
declare variable i_cle_mere_mere integer;
begin
   select  sexe,cle_pere,cle_mere
      from individu
      where cle_fiche = :i_clef
      into :i_sexe,:i_cle_pere,:i_cle_mere;
   for
   select  0,      --l'individu
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           1
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
         from individu
              where cle_fiche  = :i_clef
    union
    select 1,    --son père
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           2
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
         from individu
              where cle_fiche=(select cle_pere from individu
                                 where cle_fiche=:i_clef)
    union
    select 1,   --sa mère
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           3
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
         from individu
              where cle_fiche=(select cle_mere from individu
                                 where cle_fiche=:i_clef)
    union
    select 2,   --ses grands parents
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           sosa
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
           from proc_trouve_grands_parent(:i_clef)
   union
    select 4,  --ses frères et soeurs
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere
           ,f_1
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
           from proc_trouve_freres_soeurs(:i_clef)
    union
    select 3,
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere
           ,sosa
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
           from proc_trouve_oncles_tantes(:i_clef)
    union
    select 5,   -- ses enfants
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere
           ,annee_naissance
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
      from individu
      where (:i_sexe=1 and cle_pere=:i_clef)
         or (:i_sexe=2 and cle_mere=:i_clef)
    union
    select 7,  --ses conjoints
            p.conjoint
           ,c.nom
           ,c.prenom
           ,c.date_naissance
           ,c.date_deces
           ,c.sexe
           ,c.cle_pere
           ,c.cle_mere
           ,p.ordre
           ,c.decede
           ,c.num_sosa
           ,iif(c.annee_naissance is null and c.annee_deces is null,null,
            '('||coalesce('°'||cast(c.annee_naissance as varchar(5)),'')||
            iif(c.annee_naissance is null or c.annee_deces is null,'',' ')||
            coalesce('†'||cast(c.annee_deces as varchar(5)),'')||')')
      from proc_conjoints_ordonnes(:i_clef,0) p
        left join individu c on c.cle_fiche=p.conjoint
    union
    select 6,  --ses cousins et cousines
           i.cle_fiche,
           i.nom,
           i.prenom,
           i.date_naissance,
           i.date_deces,
           i.sexe,
           i.cle_pere,
           i.cle_mere
           ,p.sosa*10000+coalesce(i.annee_naissance,0)
           ,i.decede
           ,i.num_sosa
           ,iif(i.annee_naissance is null and i.annee_deces is null,null,
            '('||coalesce('°'||cast(i.annee_naissance as varchar(5)),'')||
            iif(i.annee_naissance is null or i.annee_deces is null,'',' ')||
            coalesce('†'||cast(i.annee_deces as varchar(5)),'')||')')
           from proc_trouve_oncles_tantes (:i_clef) p,
                individu i
           where (p.sexe=1 and i.cle_pere=p.cle_fiche)
              or (p.sexe=2 and i.cle_mere=p.cle_fiche)
    union
    select 8,  --ses petits enfants
           i.cle_fiche,
           i.nom,
           i.prenom,
           i.date_naissance,
           i.date_deces,
           i.sexe,
           i.cle_pere,
           i.cle_mere
           ,coalesce(p.annee_naissance,0)*10000+coalesce(i.annee_naissance,0)
           ,i.decede
           ,i.num_sosa
           ,iif(i.annee_naissance is null and i.annee_deces is null,null,
            '('||coalesce('°'||cast(i.annee_naissance as varchar(5)),'')||
            iif(i.annee_naissance is null or i.annee_deces is null,'',' ')||
            coalesce('†'||cast(i.annee_deces as varchar(5)),'')||')')
           from (select cle_fiche,sexe,annee_naissance
                 from individu
                 where (:i_sexe=1 and cle_pere=:i_clef)
                    or (:i_sexe=2 and cle_mere=:i_clef)) as p,
                individu i
           where (p.sexe=1 and i.cle_pere=p.cle_fiche)
              or (p.sexe=2 and i.cle_mere=p.cle_fiche)
    union
    select 9,   --ses neveux et nièces
           i.cle_fiche,
           i.nom,
           i.prenom,
           i.date_naissance,
           i.date_deces,
           i.sexe,
           i.cle_pere,
           i.cle_mere
           ,p.f_1*10000+coalesce(i.annee_naissance,0)
           ,i.decede
           ,i.num_sosa
           ,iif(i.annee_naissance is null and i.annee_deces is null,null,
            '('||coalesce('°'||cast(i.annee_naissance as varchar(5)),'')||
            iif(i.annee_naissance is null or i.annee_deces is null,'',' ')||
            coalesce('†'||cast(i.annee_deces as varchar(5)),'')||')')
           from proc_trouve_freres_soeurs (:i_clef) p,
                individu i
           where (p.sexe=1 and i.cle_pere=p.cle_fiche)
              or (p.sexe=2 and i.cle_mere=p.cle_fiche)
    order by 1,10
    into :niveau,
         :cle_fiche,
         :nom,
         :prenom,
         :date_naissance,
         :date_deces,
         :sexe,
         :cle_pere,
         :cle_mere,
         :sosa,
         :decede,
         :num_sosa,
         :periode_vie
   do
   begin
     ville_naissance=null;
     ville_deces=null;
     profession=null;
     photo=null;
     enfants=null;
     if (not(niveau=1 and sosa=3)) then
     begin
       date_union=null;
       ville_union=null;
     end
     if (niveau in (0,1,2,5,7)) then
     begin
       select first(1) ev_ind_ville
       from evenements_ind  --les villes de naissances
       where ev_ind_kle_fiche=:cle_fiche and ev_ind_type='BIRT'
       into :ville_naissance;
       select first(1) ev_ind_ville
       from evenements_ind  --les villes de décès
       where ev_ind_kle_fiche=:cle_fiche and ev_ind_type='DEAT'
       into :ville_deces;
       if (i_max=1) then
         select count(1)  --le petit média et le nombre d'enfants
           ,coalesce((select multi_reduite from multimedia
                       where multi_clef=(select first(1)mp_media from media_pointeurs
                                         where mp_cle_individu=:cle_fiche
                                           and mp_identite=1))
           ,(select multi_reduite from multimedia
             where multi_clef=(select first(1)mp_media from media_pointeurs
                               where mp_cle_individu=:cle_fiche
                               order by mp_clef desc)))
         from individu
         where (:sexe=1 and cle_pere=:cle_fiche)
            or (:sexe=2 and cle_mere=:cle_fiche)
         into :enfants
             ,:photo;
       else --i_max=3
         select count(1)  --le nombre d'enfants
         from individu
         where (:sexe=1 and cle_pere=:cle_fiche)
            or (:sexe=2 and cle_mere=:cle_fiche)
         into :enfants;
       select first(1) ev_ind_description from evenements_ind
       where ev_ind_kle_fiche=:cle_fiche and ev_ind_type='OCCU'
       order by ev_ind_ordre desc, ev_ind_datecode desc nulls last
       into :profession;

       if (niveau=1) then  --ses parents
       begin
         if (sosa=2) then  --le père
         begin
           if (i_cle_mere is not null) then
             select first(1) e.ev_fam_date_writen  --l'union des parents
                            ,e.ev_fam_ville
             from t_union u
             inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
             where u.union_mari=:i_cle_pere and u.union_femme=:i_cle_mere
             order by ev_fam_ordre,ev_fam_datecode nulls last
             into :date_union
                 ,:ville_union;
           i_cle_pere_pere=cle_pere;  --parents du père
           i_cle_mere_pere=cle_mere;
         end
         else     --la mère
         begin
           i_cle_pere_mere=cle_pere;  --parents de la mère
           i_cle_mere_mere=cle_mere;
         end
       end  --de niveau=1

       if (niveau=2) then --les grands parents
       begin
         if (sosa in(4,5)) then --parents du père
         begin
           if (i_cle_pere_pere is not null and i_cle_mere_pere is not null) then
           begin
            select first(1) e.ev_fam_date_writen   --l'union des parents du père
                           ,e.ev_fam_ville
            from t_union u
            inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
            where u.union_mari=:i_cle_pere_pere and u.union_femme=:i_cle_mere_pere
            order by ev_fam_date_year,ev_fam_date_mois,ev_fam_date
            into :date_union
                ,:ville_union;
           end  --de l'union des parents du père
         end  --des parents du père
         else --parents de la mère
         begin
           if (i_cle_pere_mere is not null and i_cle_mere_mere is not null) then
           begin
             select first(1) e.ev_fam_date_writen   --l'union des parents de la mère
                            ,e.ev_fam_ville
             from t_union u
             inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
             where u.union_mari=:i_cle_pere_mere and u.union_femme=:i_cle_mere_mere
             order by ev_fam_ordre,ev_fam_datecode nulls last
             into :date_union
                 ,:ville_union;
           end  --de l'union des parents de la mère
         end  --des parents de la mère
       end  --des grands-parents

       if (niveau=7) then  --les conjoints
       begin
         select first(1) e.ev_fam_date_writen
                        ,e.ev_fam_ville
         from t_union u
         inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
         where (:i_sexe=1 and u.union_mari=:i_clef and u.union_femme=:cle_fiche)
            or (:i_sexe=2 and u.union_mari=:cle_fiche and u.union_femme=:i_clef)
         order by ev_fam_ordre,ev_fam_datecode nulls last
         into :date_union
             ,:ville_union;
       end -- de conjoints

     end -- de (niveau in (0,1,2,5,7))
   suspend;
 end
end  ^

ALTER PROCEDURE PROC_NAVIGATION (
    I_CLEF integer,
    I_MAX integer )
RETURNS (
    NIVEAU integer,
    CLE_FICHE integer,
    NOM varchar(60),
    PRENOM varchar(100),
    DATE_NAISSANCE varchar(100),
    DATE_DECES varchar(100),
    SEXE integer,
    CLE_PERE integer,
    CLE_MERE integer,
    SOSA double precision,
    DECEDE integer,
    VILLE_NAISSANCE varchar(50),
    VILLE_DECES varchar(50),
    PROFESSION varchar(90),
    DATE_UNION varchar(90),
    VILLE_UNION varchar(50),
    PHOTO blob sub_type 0,
    ENFANTS integer,
    NUM_SOSA double precision,
    PERIODE_VIE varchar(15) )
AS
declare variable i_sexe integer;
declare variable i_cle_pere integer;
declare variable i_cle_mere integer;
declare variable i_cle_pere_pere integer;
declare variable i_cle_pere_mere integer;
declare variable i_cle_mere_pere integer;
declare variable i_cle_mere_mere integer;
begin
   select  sexe,cle_pere,cle_mere
      from individu
      where cle_fiche = :i_clef
      into :i_sexe,:i_cle_pere,:i_cle_mere;
   for
   select  0,      --l'individu
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           1
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
         from individu
              where cle_fiche  = :i_clef
    union
    select 1,    --son père
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           2
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
         from individu
              where cle_fiche=(select cle_pere from individu
                                 where cle_fiche=:i_clef)
    union
    select 1,   --sa mère
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           3
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
         from individu
              where cle_fiche=(select cle_mere from individu
                                 where cle_fiche=:i_clef)
    union
    select 2,   --ses grands parents
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere,
           sosa
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
           from proc_trouve_grands_parent(:i_clef)
   union
    select 4,  --ses frères et soeurs
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere
           ,f_1
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
           from proc_trouve_freres_soeurs(:i_clef)
    union
    select 3,
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere
           ,sosa
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
           from proc_trouve_oncles_tantes(:i_clef)
    union
    select 5,   -- ses enfants
           cle_fiche,
           nom,
           prenom,
           date_naissance,
           date_deces,
           sexe,
           cle_pere,
           cle_mere
           ,annee_naissance
           ,decede
           ,num_sosa
           ,iif(annee_naissance is null and annee_deces is null,null,
            '('||coalesce('°'||cast(annee_naissance as varchar(5)),'')||
            iif(annee_naissance is null or annee_deces is null,'',' ')||
            coalesce('†'||cast(annee_deces as varchar(5)),'')||')')
      from individu
      where (:i_sexe=1 and cle_pere=:i_clef)
         or (:i_sexe=2 and cle_mere=:i_clef)
    union
    select 7,  --ses conjoints
            p.conjoint
           ,c.nom
           ,c.prenom
           ,c.date_naissance
           ,c.date_deces
           ,c.sexe
           ,c.cle_pere
           ,c.cle_mere
           ,p.ordre
           ,c.decede
           ,c.num_sosa
           ,iif(c.annee_naissance is null and c.annee_deces is null,null,
            '('||coalesce('°'||cast(c.annee_naissance as varchar(5)),'')||
            iif(c.annee_naissance is null or c.annee_deces is null,'',' ')||
            coalesce('†'||cast(c.annee_deces as varchar(5)),'')||')')
      from proc_conjoints_ordonnes(:i_clef,0) p
        left join individu c on c.cle_fiche=p.conjoint
    union
    select 6,  --ses cousins et cousines
           i.cle_fiche,
           i.nom,
           i.prenom,
           i.date_naissance,
           i.date_deces,
           i.sexe,
           i.cle_pere,
           i.cle_mere
           ,p.sosa*10000+coalesce(i.annee_naissance,0)
           ,i.decede
           ,i.num_sosa
           ,iif(i.annee_naissance is null and i.annee_deces is null,null,
            '('||coalesce('°'||cast(i.annee_naissance as varchar(5)),'')||
            iif(i.annee_naissance is null or i.annee_deces is null,'',' ')||
            coalesce('†'||cast(i.annee_deces as varchar(5)),'')||')')
           from proc_trouve_oncles_tantes (:i_clef) p,
                individu i
           where (p.sexe=1 and i.cle_pere=p.cle_fiche)
              or (p.sexe=2 and i.cle_mere=p.cle_fiche)
    union
    select 8,  --ses petits enfants
           i.cle_fiche,
           i.nom,
           i.prenom,
           i.date_naissance,
           i.date_deces,
           i.sexe,
           i.cle_pere,
           i.cle_mere
           ,coalesce(p.annee_naissance,0)*10000+coalesce(i.annee_naissance,0)
           ,i.decede
           ,i.num_sosa
           ,iif(i.annee_naissance is null and i.annee_deces is null,null,
            '('||coalesce('°'||cast(i.annee_naissance as varchar(5)),'')||
            iif(i.annee_naissance is null or i.annee_deces is null,'',' ')||
            coalesce('†'||cast(i.annee_deces as varchar(5)),'')||')')
           from (select cle_fiche,sexe,annee_naissance
                 from individu
                 where (:i_sexe=1 and cle_pere=:i_clef)
                    or (:i_sexe=2 and cle_mere=:i_clef)) as p,
                individu i
           where (p.sexe=1 and i.cle_pere=p.cle_fiche)
              or (p.sexe=2 and i.cle_mere=p.cle_fiche)
    union
    select 9,   --ses neveux et nièces
           i.cle_fiche,
           i.nom,
           i.prenom,
           i.date_naissance,
           i.date_deces,
           i.sexe,
           i.cle_pere,
           i.cle_mere
           ,p.f_1*10000+coalesce(i.annee_naissance,0)
           ,i.decede
           ,i.num_sosa
           ,iif(i.annee_naissance is null and i.annee_deces is null,null,
            '('||coalesce('°'||cast(i.annee_naissance as varchar(5)),'')||
            iif(i.annee_naissance is null or i.annee_deces is null,'',' ')||
            coalesce('†'||cast(i.annee_deces as varchar(5)),'')||')')
           from proc_trouve_freres_soeurs (:i_clef) p,
                individu i
           where (p.sexe=1 and i.cle_pere=p.cle_fiche)
              or (p.sexe=2 and i.cle_mere=p.cle_fiche)
    order by 1,10
    into :niveau,
         :cle_fiche,
         :nom,
         :prenom,
         :date_naissance,
         :date_deces,
         :sexe,
         :cle_pere,
         :cle_mere,
         :sosa,
         :decede,
         :num_sosa,
         :periode_vie
   do
   begin
     ville_naissance=null;
     ville_deces=null;
     profession=null;
     photo=null;
     enfants=null;
     if (not(niveau=1 and sosa=3)) then
     begin
       date_union=null;
       ville_union=null;
     end
     if (niveau in (0,1,2,5,7)) then
     begin
       select first(1) ev_ind_ville
       from evenements_ind  --les villes de naissances
       where ev_ind_kle_fiche=:cle_fiche and ev_ind_type='BIRT'
       into :ville_naissance;
       select first(1) ev_ind_ville
       from evenements_ind  --les villes de décès
       where ev_ind_kle_fiche=:cle_fiche and ev_ind_type='DEAT'
       into :ville_deces;
       if (i_max=1) then
         select count(1)  --le petit média et le nombre d'enfants
           ,coalesce((select multi_reduite from multimedia
                       where multi_clef=(select first(1)mp_media from media_pointeurs
                                         where mp_cle_individu=:cle_fiche
                                           and mp_identite=1))
           ,(select multi_reduite from multimedia
             where multi_clef=(select first(1)mp_media from media_pointeurs
                               where mp_cle_individu=:cle_fiche
                               order by mp_clef desc)))
         from individu
         where (:sexe=1 and cle_pere=:cle_fiche)
            or (:sexe=2 and cle_mere=:cle_fiche)
         into :enfants
             ,:photo;
       else --i_max=3
         select count(1)  --le nombre d'enfants
         from individu
         where (:sexe=1 and cle_pere=:cle_fiche)
            or (:sexe=2 and cle_mere=:cle_fiche)
         into :enfants;
       select first(1) ev_ind_description from evenements_ind
       where ev_ind_kle_fiche=:cle_fiche and ev_ind_type='OCCU'
       order by ev_ind_ordre desc, ev_ind_datecode desc nulls last
       into :profession;

       if (niveau=1) then  --ses parents
       begin
         if (sosa=2) then  --le père
         begin
           if (i_cle_mere is not null) then
             select first(1) e.ev_fam_date_writen  --l'union des parents
                            ,e.ev_fam_ville
             from t_union u
             inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
             where u.union_mari=:i_cle_pere and u.union_femme=:i_cle_mere
             order by ev_fam_ordre,ev_fam_datecode nulls last
             into :date_union
                 ,:ville_union;
           i_cle_pere_pere=cle_pere;  --parents du père
           i_cle_mere_pere=cle_mere;
         end
         else     --la mère
         begin
           i_cle_pere_mere=cle_pere;  --parents de la mère
           i_cle_mere_mere=cle_mere;
         end
       end  --de niveau=1

       if (niveau=2) then --les grands parents
       begin
         if (sosa in(4,5)) then --parents du père
         begin
           if (i_cle_pere_pere is not null and i_cle_mere_pere is not null) then
           begin
            select first(1) e.ev_fam_date_writen   --l'union des parents du père
                           ,e.ev_fam_ville
            from t_union u
            inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
            where u.union_mari=:i_cle_pere_pere and u.union_femme=:i_cle_mere_pere
            order by ev_fam_date_year,ev_fam_date_mois,ev_fam_date
            into :date_union
                ,:ville_union;
           end  --de l'union des parents du père
         end  --des parents du père
         else --parents de la mère
         begin
           if (i_cle_pere_mere is not null and i_cle_mere_mere is not null) then
           begin
             select first(1) e.ev_fam_date_writen   --l'union des parents de la mère
                            ,e.ev_fam_ville
             from t_union u
             inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
             where u.union_mari=:i_cle_pere_mere and u.union_femme=:i_cle_mere_mere
             order by ev_fam_ordre,ev_fam_datecode nulls last
             into :date_union
                 ,:ville_union;
           end  --de l'union des parents de la mère
         end  --des parents de la mère
       end  --des grands-parents

       if (niveau=7) then  --les conjoints
       begin
         select first(1) e.ev_fam_date_writen
                        ,e.ev_fam_ville
         from t_union u
         inner join evenements_fam e on ev_fam_kle_famille=u.union_clef and ev_fam_type='MARR'
         where (:i_sexe=1 and u.union_mari=:i_clef and u.union_femme=:cle_fiche)
            or (:i_sexe=2 and u.union_mari=:cle_fiche and u.union_femme=:i_clef)
         order by ev_fam_ordre,ev_fam_datecode nulls last
         into :date_union
             ,:ville_union;
       end -- de conjoints

     end -- de (niveau in (0,1,2,5,7))
   suspend;
 end
end  ^
SET TERM ; ^

UPDATE RDB$PROCEDURES set
  RDB$DESCRIPTION = 'Procédure entièrement refaite en 2007 par André Langlet.
Dernières modifications par André le 14/3/2008 pour dates avec° et †Ɗle 07/04/2009 suppression utilisation proc_trouve_unions
le 28/12/2009 correction suite à suppression des paramètres inutiles de
PROC_TROUVE_ONCLES_TANTES et de I_DOSSIER.
le 27/03/2011 suppression des témoins
le 08/03/2012 simplification suite à utilisation datecode
I_MAX est utilisé pour définir le mode de fonctionnement
   1:: informations complètes pour grande fenêtre de navigation
   3: idem sans photos
Description :    Cette procedure permet de récuperer la famille d''un individu
   Le Niveau est le suivant:
   0 - Lui Meme
   1 - Parents
   2 - Grands Parents
   3 - Oncles et tantes
   4 - Freres et soeurs
   5 - Enfants
   6 - Cousins et cousines
   7 - Conjoints
   8 - Petits-enfants
   9 - Neveux et nièces'
  where RDB$PROCEDURE_NAME = 'PROC_NAVIGATION';

UPDATE T_VERSION_BASE SET VER_VERSION='5.172';
COMMIT WORK;

